### ISSUE TITLE
L1 Validator Account Abstraction

### ISSUE THREAD

**Issue by martineckardt** [ava-labs/icm-contracts#691]
Some critical L1 smart contracts could be `ownable`. While sticking to the OpenZeppelin implementation is familiar for many devs, there is the danger of introducing points of failures with these accounts.

To avoid giving this power to single accounts and enable L1s to move that power to their validator set, we should build account abstraction around the validator set. 

The implementation could be a smart contract that will perform arbitrary actions (like calling other smart contract’s methods protected with `onlyOwner`) ONLY if it's provided a valid off-chain warp message of the validator set specifying the contracts address, method name and parameters.

Resources:
- [Similar logic in Registry](https://github.com/ava-labs/icm-contracts/blob/main/contracts/teleporter/registry/TeleporterRegistry.sol#L101-L113)

**Comment by meaghanfitzgerald** [comment]
@michaelkaplan13 's response: 
> If I understand correctly, we already have this implemented and audit in the form of the ValidatorSetSig contract.
https://github.com/ava-labs/icm-contracts/tree/main/contracts/governance
